import type { Metadata } from "next";
import Nav from "@/pages/component/home/Nav"
import BookingForm from "@/pages/component/home/BookingForm"
import Footer from "@/pages/component/home/Footer"

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
            <Nav></Nav>
              <BookingForm></BookingForm>
        {children}
          <Footer></Footer>
      </body>
    </html>
  );
}
